bloodaccount/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.views.generic.base import TemplateView
from core.views import forgot, change_pwd, register, home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,
        {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/forgot/$', forgot, name='forgot_password'),
    url(r'^accounts/register/$', register, name='register'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'^$', home, name='home'),
    url(r'^accounts/sent/$', TemplateView.as_view(template_name='core/email_sent.html'), name='email_sent'),
    url(r'^accounts/notsent/$', TemplateView.as_view(template_name='core/not_sent.html'), name='not_sent'),
    url(r'^accounts/pwdset/$', TemplateView.as_view(template_name='core/pwd_set.html'), name='pwd_set'),
    url(r'^accounts/change_pwd/(?P<id>\d+)/$', change_pwd, name='change_pwd'),
    url(r'^account/', include('account.urls')),
    url(r'^club/', include('club.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = 'Blood Bank admin'

club/urls.py
from django.conf.urls import url

from club import views


urlpatterns = [
    url(r'profile/$', views.profile, name='club_profile'),
    url(r'info/$', views.info, name='club_info'),
    url(r'add_member/$', views.add_member),
    url(r'remove_member/(?P<id>\d+)/$', views.remove_member),
    url(r'save_order/$', views.save_order),
    url(r'cancel_match/(?P<id>\d+)/$', views.cancel_match),
    url(r'start_match/(?P<id>\d+)/$', views.start_match),
    url(r'complete_match/(?P<id>\d+)/$', views.complete_match),
    url(r'leaderboard/$', views.leaderboard),
]

account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime


class Account(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    registered_on = models.DateTimeField(default=timezone.now)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class Transaction(models.Model):
    CREDIT = 0
    DEBIT = 1

    TRANS_TYPE = enumerate(('Credit', 'Debit'))

    account = models.ForeignKey(Account)
    kind = models.PositiveIntegerField(choices=TRANS_TYPE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    trans_date = models.DateTimeField(default=timezone.now)
    comment = models.TextField(blank=True)
    processed = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.account)


class Game(models.Model):
    white = models.CharField(max_length=100)
    black = models.CharField(max_length=100)
    white_score = models.FloatField(null=True, blank=True)
    black_score = models.FloatField(null=True, blank=True)
    game_date = models.DateTimeField(default=datetime.now)

    def __unicode__(self):
        return u'{} vs {}'.format(self.white, self.black)

club/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
#from account.models import Account


class Club(models.Model):
    name = models.CharField(max_length=100)
    #account = models.ForeignKey(Account)
    captain = models.ForeignKey(User, null=True)
    last_sync = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.name.replace('-', ' ').upper()


class Member(models.Model):
    handle = models.CharField(max_length=200, unique=True)
    blitz_rating = models.CharField(max_length=10, blank=True)
    club = models.ForeignKey(Club)
    order = models.PositiveIntegerField('Board Order', null=True, blank=True)

    def __unicode__(self):
        return self.handle

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.models import User

from account.models import Account


class EmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        if 'email' in self.cleaned_data:
            email = self.cleaned_data['email']
            try:
                usr = User.objects.get(username=email)
            except User.DoesNotExist:
                raise forms.ValidationError(
                    'The email you entered does not exist in our records')
            else:
                return usr


class ChangePwdForm(forms.Form):
    pwd1 = forms.CharField(
        max_length=50, min_length=5, widget=forms.PasswordInput)
    pwd2 = forms.CharField(
        max_length=50, min_length=5, widget=forms.PasswordInput)

    def clean(self):
        if 'pwd1' in self.cleaned_data and 'pwd2' in self.cleaned_data:
            if self.cleaned_data['pwd1'] != self.cleaned_data['pwd2']:
                raise forms.ValidationError(
                    'Please enter the same value in both fields')
            return self.cleaned_data


class RegisterForm(forms.ModelForm):
    pwd1 = forms.CharField(max_length=50, widget=forms.PasswordInput())
    pwd2 = forms.CharField(max_length=50, widget=forms.PasswordInput())

    class Meta:
        model = Account
        fields = ['name', 'email', 'phone']

    def clean_email(self):
        if 'email' in self.cleaned_data:
            email = self.cleaned_data['email']
            try:
                User.objects.get(username=email)
            except User.DoesNotExist:
                return email
            else:
                raise forms.ValidationError('The email you are using is already taken')

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib import messages
from django.core.urlresolvers import reverse

from core.forms import EmailForm, ChangePwdForm, RegisterForm


@login_required
def home(request):
    return render(
        request,
        'core/home.html',
        {'login': request.user.last_login})


def forgot(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            usr = form.cleaned_data['email']
            token = default_token_generator.make_token(usr)
            host = request.get_host()
            _url = reverse('change_pwd', args=[usr.id])
            reset_link = 'http://{}{}?token={}'.format(host, _url, token)
            msg = 'Someone asked to reset your password. If it was not you, you can ignore this message else use this link to reset your password {}'.format(reset_link)
            try:
                send_mail(
                    'Reset Password',
                    msg,
                    'drug-exchange@everyday.com.ng',
                    [usr.username])
            except:
                return redirect('not_sent')

            # Send email
            return redirect('email_sent')
    else:
        form = EmailForm()
    return render(request, 'core/forgot.html', {'form': form})


def change_pwd(request, id):
    user = get_object_or_404(User, pk=id)
    token = request.GET.get('token')
    if not token:
        messages.error(request, 'Invalid request')
    else:
        is_valid_token = default_token_generator.check_token(user, token)
        if not is_valid_token:
            messages.error(request, 'Invalid request')
    if request.method == 'POST' and token and is_valid_token:
        form = ChangePwdForm(request.POST)
        if form.is_valid():
            pwd = form.cleaned_data['pwd1']
            user.set_password(pwd)
            user.save()
            return redirect('pwd_set')
    else:
        form = ChangePwdForm()
    return render(request, 'core/change_pwd.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            #import pdb;pdb.set_trace()
            pwd = form.cleaned_data.pop('pwd1')
            email = form.cleaned_data['email']
            #referrer = form.cleaned_data['referrer']
            #pharmacy = form.save(commit=False)
            account = form.save(commit=False)
            usr = User.objects.create_user(
                username=email,
                password=pwd,
                first_name=form.cleaned_data['name'])
            account.user = usr
            account.balance = 5000
            account.save()

            messages.success(
                request, 'Welcome to the Blood bank!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'core/register.html', {'form': form})

templates/core/alt_base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="google-site-verification" content="NKmLZomMQQYwT72sHvkIeKmli2fQ8CQkeW6HKRtMtL8" />
  <title>KFDMS | {% block title %}Login{% endblock title %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta contentdth=device-width, initial-scale=1, maximum-scale=1, user-scalable="no" name="viewport">
  {% block css %}
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect.
  -->
  <link rel="stylesheet" href="{% static 'css/skins/skin-red-light.min.css' %}">
  <!-- Jquery ui -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="{% static 'js/vue.min.js' %}"></script>
  <script src="https://unpkg.com/vue-resource@1.3.1/dist/vue-resource.min.js"></script>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <style>
    .content-wrapper, .main-footer {
      margin-left: 0;
    }
    .skin-red-light .main-header .navbar {
        background-color: #DC042A;
    }
    .skin-red-light .main-header .logo {
        background-color: #DC042A;
        color: #fff;
        border-bottom: 0 solid transparent;
    }
</style>
  {% endblock css %}

  {% block extra-css %}
  
  {% endblock extra-css %}

  {% block top-js %}
  {% endblock top-js %}
  
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-red-light sidebar-collapse">
  
<div class="wrapper">


  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="{% url 'home' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>B</b>B</span>
      <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">
        <img class="img-responsive" style="margin-left: auto; margin-right: auto;
      display: block;" src="{% static 'img/bb_logo.png' %}" alt=""> </span>
      
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
     <!--  <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a> -->
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- Messages: style can be found in dropdown.less-->
        


        
   
          <!-- Control Sidebar Toggle Button -->
          
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
     
     
    </section>

    <!-- Main content -->
    <section class="content">
      {% block main-content %}
      
      {% endblock main-content %}

      <!-- Your Page Content Here -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      blood-bank
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">Blood Bank</a>.</strong> All rights reserved.
  </footer>

</div>
<!-- ./wrapper -->

{% block js %}

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/Chart.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/app.min.js' %}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
{% endblock js %}

{% block extra-js %}

{% endblock extra-js %}
</body>
</html>

templates/core/change_pwd.html
{% extends "core/alt_base.html" %}
{% load static from staticfiles %}

{% block page-header %}
    Change Password
{% endblock page-header %}

{% block title %}
    Change Password
{% endblock title %}

{% block main-content %}
<div class="login-box">
  <div class="login-logo">
  
  <span class="logo-lg">Drug Xchange
  </span>
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Password reset</p>

<form action="" method="post">{% csrf_token %}
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error }}
          </div>
      {% endfor %}
    {% endif %}
    <div class="form-group has-feedback">
      {% if form.pwd1.errors %}
        <div class="alert alert-danger">
          {{ form.pwd1.errors }}
        </div>
      {% endif %}
      {{ form.pwd1 }}
      <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    
    <div class="form-group has-feedback">
      {% if form.pwd2.errors %}
        <div class="alert alert-danger">
          {{ form.pwd2.errors }}
        </div>
      {% endif %}
      {{ form.pwd2 }}
       <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
      
      <div class="row">
          <button type="submit" class="btn btn-danger btn-block btn-flat"><i class="fa fa-key"></i> Change Password</button>
      </div>
    </form>

    <!-- /.social-auth-links -->
    <div class="row">
    <p>I think I remember my password <a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Sign in</a></p>
    <p>I don't have an account <a href="#">Register</a></p>
    </div>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{% endblock main-content %}

{% block extra-js %}
<script>
  $('#id_pwd1').attr('placeholder', 'New Password');
  $('#id_pwd1').addClass('form-control');

  $('#id_pwd2').attr('placeholder', 'Confirm Password');
  $('#id_pwd2').addClass('form-control');
  </script>
{% endblock extra-js %}

templates/core/email_sent.html
{% extends "core/alt_base.html" %}
{% load staticfiles %}


{% block page-header %}
Email Sent
{% endblock page-header %}

{% block main-content %}
<div class="login-box">
  <div class="login-logo">
  
  <span class="logo-lg">Drug Xchange
  </span>
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
      <div class="fa fa-3x fa-envelope text-green" style="margin: auto; width: 100%; text-align:center;"></div>
      <h4 style="text-align:center;">We have sent an email to you with with instructions on how to change your password.</h4>
      <p style="text-align:center;" class="text-red">Make sure to check your spam folder if you can't find the mail.</p>
    <!-- /.social-auth-links -->
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{% endblock main-content %}

templates/core/forgot.html
{% extends "core/alt_base.html" %}
{% load staticfiles %}

{% block breadcrumb %}
<li class="active">Sign In</li>
{% endblock breadcrumb %}

{% block page-header %}
  Password recovery
{% endblock page-header %}

{% block main-content %}
<div class="login-box">
  <div class="login-logo">
  
  <span class="logo-lg">Drug Xchange
  </span>
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Password reset</p>

    <form action="" method="post">{% csrf_token %}
    {% if form.non_field_errors %}
    	{% for error in form.non_field_errors %}
    		<div class="alert alert-danger">
    			{{ error }}
    		</div>
    	{% endfor %}
    {% endif %}
      <div class="form-group has-feedback">
      	{% if form.email.errors %}
      		<div class="alert alert-danger">
      			{{ form.email.errors }}
      		</div>
        <!-- <input type="password" class="form-control" placeholder="Password"> -->
        {% endif %}
        {{ form.email }}
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        <span class="text-muted"><small>We will send you a mail with instructions on how to reset your password</small></span>
      </div>

      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <!-- <input type="checkbox"> Remember Me -->
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="">
        	<button type="submit" class="btn btn-block btn-danger btn-flat"><i class="fa fa-envelope"></i> Send me a recovery mail</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <!-- /.social-auth-links -->
    <div class="row">
    <p>I think I remember my password <a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Sign in</a></p>
    <p>I don't have an account <a href="#">Register</a></p>
    </div>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{% endblock main-content %}


{% block extra-js %}
<script>
  $('#id_email').attr('placeholder', 'Email');
  $('#id_email').addClass('form-control');

  </script>
{% endblock extra-js %}

templates/core/login.html
{% extends "core/base.html" %}
{% load static from staticfiles %}

{% block extra-js %}
        <script type="text/javascript">
        $(function(){
                $('#id_username').attr('placeholder', 'E-mail');
                $('#id_username').attr('class', 'form-control');
                $('#id_password').attr('placeholder', 'Password');
                $('#id_password').attr('class', 'form-control');
        });
        </script>
{% endblock extra-js %}

                    {% block innerbody %}
                    {% if form.non_field_errors %}
                    <div class="form-group has-error">
                        <label class="control-label">{{ form.non_field_errors }}</label>
                    </div>
                    {% endif %}
                    <div class="login-title"><strong>Log In</strong> to your account</div>
                    <form action="" class="form-horizontal" method="post">{% csrf_token %}
                    <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.username.errors %}
                              <label class="control-label">{{ form.username.errors }}</label>
                            {% endif %}
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.password.errors %}
                              <label class="control-label">{{ form.password.errors }}</label>
                            {% endif %}
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <a href="{% url 'registration' %}" class="btn btn-link btn-block">Register</a>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-block btn-primary">Log In</button>
                        </div>
                    </div>
                    </form>
                    <div class="login-or">OR</div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <a href="{% url 'twtlogin' %}"><button class="btn btn-info btn-block btn-twitter"><span class="fa fa-twitter"></span>Twitter</button></a>
                        </div>
                        <div class="col-md-4">
                            <a href="{% url 'fblogin' %}"><button class="btn btn-info btn-block btn-facebook"><span class="fa fa-facebook"></span> Facebook</button></a>
                        </div>
                        <div class="col-md-4">                            
                            <a href="{% url 'gplogin' %}"><button class="btn btn-info btn-block btn-google"><span class="fa fa-google-plus"></span> Google</button></a>
                        </div>
                    </div>
                    <div class="login-subtitle">
                        Don't have an account yet? <a href="#">Create an account</a>
                    </div>
                    
                    {% endblock innerbody %}

templates/core/not_sent.html
{% extends "core/alt_base.html" %}
{% load staticfiles %}


{% block page-header %}
Email Sent
{% endblock page-header %}

{% block main-content %}
<div class="login-box">
  <div class="login-logo">
  
  <span class="logo-lg">Drug Xchange
  </span>
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
      <div class="fa fa-3x fa-close text-red" style="margin: auto; width: 100%; text-align:center;"></div>
      <h4 style="text-align:center;">There was an issue sending the email, please  <a href="mailto:bayokrapht@gmail.com">contact the admin.</a></h4>
    <!-- /.social-auth-links -->
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{% endblock main-content %}

templates/core/pwd_set.html
{% extends "core/alt_base.html" %}
{% load staticfiles %}


{% block page-header %}
Email Sent
{% endblock page-header %}

{% block main-content %}
<div class="login-box">
  <div class="login-logo">
  
  <span class="logo-lg">Drug Xchange
  </span>
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
      <div class="fa fa-3x fa-check text-green" style="margin: auto; width: 100%; text-align:center;"></div>
      <h4 style="text-align:center;">Your password has been reset successfully!</h4>
      <p style="text-align:center;"><a href="{% url 'login' %}">Proceed to login</a></p>
      
    <!-- /.social-auth-links -->
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{% endblock main-content %}

templates/core/register.html
{% extends "core/alt_base.html" %}
{% load staticfiles %}

{% block breadcrumb %}
<li class="active">Join us</li>
{% endblock breadcrumb %}

{% block page-header %}
  Register
{% endblock page-header %}

{% block main-content %}
<div class="login-box">
  <div class="login-logo">
  
  <span class="logo-lg">Blood Bank
  </span>
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Join the Blood Bank network</p>

    <form action="" method="post">{% csrf_token %}
    {% if form.non_field_errors %}
    	{% for error in form.non_field_errors %}
    		<div class="alert alert-danger">
    			{{ error }}
    		</div>
    	{% endfor %}
    {% endif %}
     

      <div class="form-group has-feedback">
        {% if form.email.errors %}
            <div class="alert alert-danger">
                {{ form.email.errors }}
            </div>
        {% endif %}
        {{ form.email }}
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
          {% if form.pwd1.errors %}
            <div class="alert alert-danger">
                {{ form.pwd1.errors }}
            </div>
        {% endif %}
        {{ form.pwd1 }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        
      </div>

        <div class="form-group has-feedback">
          {% if form.pwd2.errors %}
            <div class="alert alert-danger">
                {{ form.pwd2.errors }}
            </div>
        {% endif %}
        {{ form.pwd2 }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        
      </div>

       <hr />

        <div class="form-group has-feedback">
        {% if form.name.errors %}
            <div class="alert alert-danger">
                {{ form.name.errors }}
            </div>
        {% endif %}
        {{ form.name }}
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
          {% if form.phone.errors %}
            <div class="alert alert-danger">
                {{ form.phone.errors }}
            </div>
        {% endif %}
        {{ form.phone }}
        <span class="glyphicon glyphicon-earphone form-control-feedback"></span>
        
      </div>

       <div class="form-group has-feedback">
        {% if form.address.errors %}
            <div class="alert alert-danger">
                {{ form.address.errors }}
            </div>
        {% endif %}
        {{ form.address }}
      </div>

      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <!-- <input type="checkbox"> Remember Me -->
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="">
        	<button type="submit" class="btn btn-block btn-danger btn-flat"><i class="fa fa-sign-in"></i> Join us!</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <!-- /.social-auth-links -->
    <div class="row">
    <p>I already have an account <a href="{% url 'login' %}">Login</a></p>
    </div>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{% endblock main-content %}


{% block extra-js %}
<script>
    $('#id_name').attr('placeholder', 'Your Name');
    $('#id_name').addClass('form-control');

    $('#id_email').attr('placeholder', 'Email (will be used to login)');
    $('#id_email').addClass('form-control');

    $('#id_pwd1').addClass('form-control');
    $('#id_pwd1').attr('placeholder', 'Password');
    
    $('#id_pwd2').addClass('form-control');
    $('#id_pwd2').attr('placeholder', 'Verify Password');

    $('#id_phone').attr('placeholder', 'Mobile');
    $('#id_phone').addClass('form-control');

    $('#id_address').attr('placeholder', 'Address');
    $('#id_address').attr('rows', '4');
    $('#id_address').addClass('form-control');
    
    $('#id_state').addClass('form-control');
  </script>
{% endblock extra-js %}